# ----------------------------------------
# CORE YAML
# ----------------------------------------
logging:
    level:
# DEBUG < INFO < WARN < ERROR < FATAL
        #root: WARN
        root: FATAL
        #org.springframework.security: INFO
        org.springframework.security: FATAL

# ----------------------------------------
# SPRING YAML
# ----------------------------------------
spring:
    
    # DATA REST
    data:
        rest:
            base-path: /api

    # DATASOURCE
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:D:/Use/sqlite/financial.db
        #driver-class-name: com.mysql.jdbc.Driver
        #password: root
        #url: jdbc:mysql://127.0.0.1:3306/financial?characterEncoding=utf8&useSSL=true
        #username: root

    # HTTP encoding
    http:
        encoding:
            enabled: true
            charset: UTF-8

    # JPA
    jpa:
        hibernate:
            #ddl-auto: create-drop
            #ddl-auto: update
            ddl-auto: none
        database-platform: com.financial.SQLiteDialect
        show-sql: true

# ----------------------------------------
# WEB YAML
# ----------------------------------------
server:
    # server error.
    port: 8888